version: '3.8'

services:
  movies:
    image: movies-image
    build:
      context: ./movies
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MONGODB_APP_ID=application-mflix-yqrpksi
      - REDIS_URL=redis://redis:6379    
    networks:
      - cache-tier
      - general

  redis:
    image: redis:alpine    
    networks:
      - cache-tier

  random-movies:
    image: random-movies-image
    build:
      context: ./random-movies
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    environment:
      - PORT=3000        
      - URL_MOVIES=http://movies:3000
    depends_on:
      - movies
    networks:
      - general
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbit-tier      
  
  history:
    image: history-image
    build:
      context: ./historial
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"    
    networks:      
      - general

  frontend:
    image: frontend-image
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_URL_MOVIES=http://localhost:3003
        - VITE_URL_RANDOM_MOVIES=http://localhost:3000
        - VITE_URL_HISTORY=http://localhost:8080
        - VITE_URL_PROXY=http://localhost:3002
        - VITE_CLICKS_COUNT=5
    ports:
      - "80:80"
    depends_on:
      - movies
      - random-movies
      - history
      - proxy
    networks:
      - general
      
  proxy:
    image: proxy-image
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - RANDOM_MOVIES_URL=http://random-movies:3000
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - RABBITMQ_MOVIES_QUEUE=movies
      - RABBITMQ_RECOMMENDATIONS_QUEUE=recommendation
    depends_on:
      - rabbitmq
    networks:
      - rabbit-tier
      - general
  
  recommender:
    image: recommender-image
    build:
      context: ./recomendador
      dockerfile: Dockerfile    
    environment:
      - RABBITMQ_HOST=amqp://admin:admin@rabbitmq:5672
      - QUEUE_MOVIES=movies
      - QUEUE_RECOMMENDATIONS=recommendation
      - LIMIT_MOVIES=5
      - LIMIT_MOVIES_SEARCH=1000
      - URL_MOVIES=http://movies:3000
    depends_on:
      - rabbitmq
      - proxy
    networks:
      - rabbit-tier
      - general

networks:
  cache-tier:
    driver: bridge
  rabbit-tier:
    driver: bridge
  general:
    driver: bridge
