#version: '3.8'

services:
  movies:
    image: movies-image
    build:
      context: ./movies
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MONGODB_APP_ID=application-mflix-yqrpksi
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" # Se exponen los puertos de rabbitmq solo para test, luego se ocultan
    networks:
      - cache-tier
      - general

  redis:
    image: redis:alpine    
    networks:
      - cache-tier

  random-movies:
    image: random-movies-image
    build:
      context: ./random-movies
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - URL_MOVIES=http://movies:3000
    depends_on:
      - movies
    networks:
      - general
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Se exponen los puertos de rabbitmq solo para test, luego se ocultan
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbit-tier      
  
  history:
    image: history-image
    build:
      context: ./historial
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on: 
      - rabbitmq
    networks:
      - rabbit-tier
      - general

  recommendation:
    image: recommender-image
    build:
      context: ./recomendador
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    env_file:
      - ./recomendador/.env
    depends_on: 
      - history
      - rabbitmq
      - movies
    networks:
      - rabbit-tier
      - general
      
  frontend:
    image: frontend-image
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_URL_MOVIES= http://localhost:3000
        - VITE_URL_HISTORY= http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - random-movies
      - history
    networks:
      - general

networks:
  cache-tier:
    driver: bridge
  rabbit-tier:
    driver: bridge
  general:
    driver: bridge
