version: '3.8'

services:
  movies:
    image: movies-image
    build:
      context: ./movies
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MONGODB_APP_ID=application-mflix-yqrpksi
      - REDIS_URL=redis://redis:6379
    networks:
      - cache-tier
      - general

  redis:
    image: redis:alpine    
    networks:
      - cache-tier

  random-movies:
    image: random-movies-image
    build:
      context: ./random-movies
      dockerfile: Dockerfile         
    ports:
      - "3000:8080"
    environment:      
      - URL_MOVIES=http://movies:3000
    depends_on:
      - movies
    networks:
      - general

networks:
  cache-tier:
    driver: bridge
  general:
    driver: bridge
